apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w5z9jgb88-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:ea60a891a923cdb1d42f219b57864a10421251f4@sha256:9f7d3b281db274bf715f3ffb87cfc121edde7b7f479e608be6d14d524fcfd670
          name: container-image
